### ISSUE TITLE
插件无法载入

### ISSUE THREAD

**Issue by Bearlele** [TISUnion/PrimeBackup#12]
系统环境：
Debian 11
Python 3.9.2
MCDReforged 2.12.3

错误信息：
> [MCDR] [17:00:00] [TaskExecutor/ERROR] [prime_backup]: Prime Backup initialization failed and will be disabled
[MCDR] [17:00:00] [TaskExecutor/INFO] [prime_backup]: Shutting down everything...
[MCDR] [17:00:00] [TaskExecutor/INFO] [prime_backup]: Shutdown completes
[MCDR] [17:00:00] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=prime_backup@1.6.3,priority=1000,callback=<function on_load at 0x7f66175cfc10>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mcdreforged/plugin/plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.9/site-packages/mcdreforged/plugin/plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "plugins/PrimeBackup-v1.6.3.pyz/prime_backup/mcdr/entrypoint.py", line 42, in on_load
    config = server.load_config_simple(target_class=Config, failure_policy='raise')
  File "/usr/local/lib/python3.9/site-packages/mcdreforged/plugin/server_interface.py", line 1184, in load_config_simple
    read_data: dict = dict_loader.load(file_handler)
  File "/usr/local/lib/python3.9/site-packages/mcdreforged/plugin/server_interface.py", line 1093, in load
    return json.load(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 16 column 23 (char 370)

**Comment by Fallen-Breath** [comment]
配置文件填写有误，json 格式非法。见错误信息最后一行

```
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 16 column 23 (char 370)
```
