### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by Worldy-MCX** [TISUnion/PrimeBackup#2]
加载不了插件，这个报错是怎么回事

系统环境：wsl
Ubuntu 18.04.6 LTS
python3.9.0
pip 23.3.1
mcdreforged 2.12.1

报错信息：
> !!MCDR plugin reload prime_backup
[MCDR] [12:47:11] [TaskExecutor/INFO]: 正在重载插件 prime_backup@1.0.1
[MCDR] [12:47:11] [TaskExecutor/INFO]: 插件 prime_backup@1.0.1 已卸载
[MCDR] [12:47:11] [TaskExecutor/INFO]: 插件 prime_backup@1.0.1 已重载
[MCDR] [12:47:11] [TaskExecutor/ERROR]: Fail to load the entry point of prime_backup@1.0.1
Traceback (most recent call last):
  File "/home/worldy/.local/lib/python3.9/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 76, in _on_ready
    self._load_entry_instance()
  File "/home/worldy/.local/lib/python3.9/site-packages/mcdreforged/plugin/type/regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
  File "/home/worldy/.local/lib/python3.9/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 44, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins/PrimeBackup-v1.0.1.pyz/prime_backup/mcdr/entrypoint.py", line 7, in <module>
    from prime_backup.compressors import CompressMethod
  File "<frozen zipimport>", line 259, in load_module
  File "plugins/PrimeBackup-v1.0.1.pyz/prime_backup/compressors.py", line 4, in <module>
    import lzma
  File "/usr/local/lib/python3.9/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

**Comment by Worldy-MCX** [comment]
解决了，之前用的是python3.9.0，现在重新编译python3.9.18，安装后可以正常加载插件了

**Comment by Fallen-Breath** [comment]
请确保所使用的 Python 环境正确包含了所有的 Python 标准库
