### ISSUE TITLE
prime_backup Error

### ISSUE THREAD

**Issue by NikolaJyun** [TISUnion/PrimeBackup#40]
[MCDR] [02:34:02] [TaskExecutor/ERROR] [prime_backup]: Prime Backup initialization failed and will be disabled
[MCDR] [02:34:02] [TaskExecutor/INFO] [prime_backup]: Shutting down everything...
[MCDR] [02:34:02] [TaskExecutor/INFO] [prime_backup]: Shutdown completes
[MCDR] [02:34:02] [TaskExecutor/ERROR]: Error invoking listener EventListener(plugin='prime_backup@1.8.1', callback=<function on_load at 0x75006cc53ac0>, priority=1000)
Traceback (most recent call last):
  File "/home/cs2server/.local/lib/python3.10/site-packages/mcdreforged/plugin/plugin_manager.py", line 737, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/home/cs2server/.local/lib/python3.10/site-packages/mcdreforged/plugin/plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "plugins/PrimeBackup-v1.8.1.pyz/prime_backup/mcdr/mcdr_entrypoint.py", line 44, in on_load
    config = server.load_config_simple(target_class=Config, failure_policy='raise')
  File "/home/cs2server/.local/lib/python3.10/site-packages/mcdreforged/plugin/si/plugin_server_interface.py", line 282, in load_config_simple
    read_data = config_handler.load(encoding=encoding)
  File "/home/cs2server/.local/lib/python3.10/site-packages/mcdreforged/plugin/si/_simple_config_handler.py", line 59, in load
    return self.__loader(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 29 column 6 (char 689)

**Comment by Fallen-Breath** [comment]
```
json.decoder.JSONDecodeError: Extra data: line 29 column 6 (char 689)
```

配置文件格式错误，不满足 json 语法，请自行解决

**Comment by NikolaJyun** [comment]
謝謝!

**Comment by NikolaJyun** [comment]
@Fallen-Breath 重新配置后 没有报错但!!pb也没有反应
