### ISSUE TITLE
无法加载prime_backup

### ISSUE THREAD

**Issue by wfanan** [TISUnion/PrimeBackup#44]
PS C:\Users\Administrator.DESKTOP-TIFIOVU\Desktop\m> mcdreforged
MCDReforged 2.13.1 is starting up
MCDReforged is open source, u can find it here: https://github.com/MCDReforged/MCDReforged
[MCDR] [13:44:12] [MainThread/INFO]: 语言已设置为 zh_cn
[MCDR] [13:44:12] [MainThread/INFO]: 编码 / 解码方式已设置为 utf8 / utf8
[MCDR] [13:44:12] [MainThread/INFO]: 解析处理器已设置为 bukkit_handler
[MCDR] [13:44:12] [MainThread/INFO]: 插件文件夹列表:
[MCDR] [13:44:12] [MainThread/INFO]: - plugins
[MCDR] [13:44:12] [MainThread/INFO]: MCDReforged 2.13.1 正在启动
[MCDR] [13:44:12] [MainThread/INFO]: MCDReforged 正于 Python 3.8.6 环境中运行
[MCDR] [13:44:12] [TaskExecutor/INFO]: 已从缓存文件加载插件仓库元数据 (更新于 2024-09-17 13:01:45)
[MCDR] [13:44:12] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [13:44:12] [TaskExecutor/INFO]: 插件 bot@1.2.4 已加载
[MCDR] [13:44:12] [TaskExecutor/INFO]: 插件 here@1.2.2 已加载
[MCDR] [13:44:12] [TaskExecutor/INFO]: 插件 location_marker@1.3.2 已加载
[MCDR] [13:44:12] [TaskExecutor/INFO]: 插件 lowercase_mcdr_command@1.2.2 已加载
[MCDR] [13:44:12] [TaskExecutor/INFO]: 插件 minecraft_data_api@1.6.1 已加载
[MCDR] [13:44:12] [TaskExecutor/INFO]: 插件 more_command_nodes@1.1.2 已加载
[MCDR] [13:44:12] [TaskExecutor/INFO]: 插件 prime_backup@1.8.2 已加载
[MCDR] [13:44:12] [TaskExecutor/INFO]: 插件 ye_announcement@1.4.1 已加载
[MCDR] [13:44:12] [TaskExecutor/ERROR]: Fail to load the entry point of prime_backup@1.8.2
Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 86, in _on_ready
    self._load_entry_instance()
  File "c:\program files\python\lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 79, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
  File "c:\program files\python\lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 51, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins\PrimeBackup-v1.8.2.pyz\prime_backup\mcdr\mcdr_entrypoint.py", line 11, in <module>
    from prime_backup.mcdr.command.commands import CommandManager
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins\PrimeBackup-v1.8.2.pyz\prime_backup\mcdr\command\commands.py", line 10, in <module>
    from prime_backup.mcdr.command.backup_id_suggestor import BackupIdSuggestor
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins\PrimeBackup-v1.8.2.pyz\prime_backup\mcdr\command\backup_id_suggestor.py", line 9, in <module>
    from prime_backup.mcdr.task_manager import TaskManager
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins\PrimeBackup-v1.8.2.pyz\prime_backup\mcdr\task_manager.py", line 16, in <module>
    from prime_backup.mcdr.task_queue import TaskQueue, TaskHolder, TaskCallback
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins\PrimeBackup-v1.8.2.pyz\prime_backup\mcdr\task_queue.py", line 20, in <module>
    class TaskHolder(Generic[_T]):
  File "plugins\PrimeBackup-v1.8.2.pyz\prime_backup\mcdr\task_queue.py", line 24, in TaskHolder
    future: futures.Future[_T] = dataclasses.field(default_factory=futures.Future)
TypeError: 'type' object is not subscriptable
[MCDR] [13:44:13] [TaskExecutor/INFO] [minecraft_data_api]: 配置文件已加载
[MCDR] [13:44:13] [TaskExecutor/INFO] [bot]: 配置文件已加载
[MCDR] [13:44:13] [TaskExecutor/INFO] [here]: 配置文件已加载
[MCDR] [13:44:13] [TaskExecutor/INFO] [location_marker]: 配置文件已加载
[MCDR] [13:44:13] [TaskExecutor/INFO]: 共加载: 8 个插件; 已加载插件数: 10
[MCDR] [13:44:13] [MainThread/INFO]: 正在启动服务端，启动参数为 'java -Xmx12G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -jar 1.21.jar --nogui'
[MCDR] [13:44:13] [MainThread/INFO]: 服务端正在以 PID 18752 运行中
[Server] Error: Unable to access jarfile 1.21.jar
[MCDR] [13:44:13] [MainThread/INFO]: 服务端进程返回代码: 1
[MCDR] [13:44:13] [MainThread/INFO]: 服务端已关闭
[MCDR] [13:44:13] [MainThread/INFO]: 正在关闭 MCDR
[MCDR] [13:44:13] [MainThread/INFO]: bye

**Comment by wfanan** [comment]
PrimeBackup 1.8.2
MCDR 2.13.1 
Python 3.8.6
windows 11 专业版
MC 服务端 Leaves 1.21.1

**Comment by Fallen-Breath** [comment]
有个 a318ace53c9ab514188b17e71e908b168440a013 引入的改没做好 python3.8 的兼容，我修复一下
