### ISSUE TITLE
无法加载prime_backup

### ISSUE THREAD

**Issue by Mingxi-Lin** [TISUnion/PrimeBackup#45]
本来能正常用的，后面突然用不了，直接安装运行的。
系统环境：
Debian 11
python 3.9.2
mcdreforged 2.13.2
下面是日志：

```
[MCDR] [2024-10-18 13:12:10.467] [MainThread/INFO] [mcdr_server.py:615(__on_mcdr_start)]: MCDReforged 2.13.2 正在启动
 [MCDR] [2024-10-18 13:12:10.469] [MainThread/INFO] [python_plugin.py:36(load)]: MCDReforged 正于 Python 3.9.2 环境中运行
 [MCDR] [2024-10-18 13:12:10.481] [TaskExecutor/INFO] [meta_holder.py:203(__load_cached_file)]: 已从缓存文件加载插件仓库元数据 >(更新于 2024-10-08 11:44:46)
 [MCDR] [2024-10-18 13:12:10.482] [TaskExecutor/INFO] [plugin_manager.py:693(refresh_all_plugins_action)]: 刷新所有插件中
 [MCDR] [2024-10-18 13:12:10.482] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 minecraft_command_register@2.13.2 已加载
 [MCDR] [2024-10-18 13:12:10.483] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 online_player_api@1.0.0 已加载
 [MCDR] [2024-10-18 13:12:10.491] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 player_last_play@1.2.0 已加载
 [MCDR] [2024-10-18 13:12:10.491] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 ledger_cleaner@0.1.0 已加载
 [MCDR] [2024-10-18 13:12:10.492] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 auto_plugin_reloader@2.0.0 已加载
 [MCDR] [2024-10-18 13:12:10.495] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 prime_backup@1.8.3 已加载
 [MCDR] [2024-10-18 13:12:10.496] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 minecraft_data_api@1.6.1 已加载
 [MCDR] [2024-10-18 13:12:10.497] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 where_is@2.2.1 已加载
 [MCDR] [2024-10-18 13:12:10.801] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [where_is]: 配置文件已加载
 [MCDR] [2024-10-18 13:12:10.809] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [player_last_play]: 配置文件已加载
 [MCDR] [2024-10-18 13:12:10.810] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [player_last_play]: 配置文件已加载
 [MCDR] [2024-10-18 13:12:10.810] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [ledger_cleaner]: 配置文件已加载
 [MCDR] [2024-10-18 13:12:10.810] [TaskExecutor/INFO] [operation.py:37(__init__)] [ledger_cleaner]: ledger sqlite checked.
 [MCDR] [2024-10-18 13:12:10.814] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [auto_plugin_reloader]: 配置文件已加载
 [MCDR] [2024-10-18 13:12:10.814] [APR@0800/INFO] [reloader.py:102(thread_loop)] [auto_plugin_reloader]: Auto Plugin Reloader @ 0800 started
 [MCDR] [2024-10-18 13:12:10.816] [TaskExecutor/ERROR] [mcdr_entrypoint.py:65(on_load)] [prime_backup]: Prime Backup initialization failed and will be disabled
 [MCDR] [2024-10-18 13:12:10.816] [TaskExecutor/INFO] [mcdr_entrypoint.py:84(on_unload)] [prime_backup]: Shutting down everything...
 [MCDR] [2024-10-18 13:12:10.817] [TaskExecutor/INFO] [mcdr_entrypoint.py:121(on_unload)] [prime_backup]: Shutdown completes
 [MCDR] [2024-10-18 13:12:10.817] [TaskExecutor/ERROR] [plugin_manager.py:739(trigger_listener)]: Error invoking listener EventListener(plugin='prime_backup@1.8.3', callback=<function on_load at 0x7f70234efd30>, priority=1000)
 Traceback (most recent call last):
 >
  >>File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/plugin_manager.py", line 737, in trigger_listener
    listener.callback(listener.plugin.server_interface, *args)
    File "plugins/PrimeBackup-v1.8.3.pyz/prime_backup/mcdr/mcdr_entrypoint.py", line 44, in on_load
    config = server.load_config_simple(target_class=Config, failure_policy='raise')
    File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/si/plugin_server_interface.py", line 307, in load_config_simple
    result_config = target_class.deserialize(read_data, missing_callback=set_imperfect, redundancy_callback=set_imperfect)
    File "plugins/PrimeBackup-v1.8.3.pyz/prime_backup/config/config.py", line 83, in deserialize
    return super().deserialize(data, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/mcdreforged/utils/serializer.py", line 447, in deserialize
    return deserialize(data, cls, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/mcdreforged/utils/serializer.py", line 297, in deserialize
    set_result_attr(attr_name, deserialize(data[attr_name], attr_type, **kwargs))
    File "/usr/local/lib/python3.9/dist-packages/mcdreforged/utils/serializer.py", line 297, in deserialize
    set_result_attr(attr_name, deserialize(data[attr_name], attr_type, **kwargs))
    File "/usr/local/lib/python3.9/dist-packages/mcdreforged/utils/serializer.py", line 226, in deserialize
    return cls(data)
    File "plugins/PrimeBackup-v1.8.3.pyz/prime_backup/types/units.py", line 179, in __new__
    raise TypeError(type(s))
>
>TypeError: <class 'NoneType'>
 [MCDR] [2024-10-18 13:12:10.817] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [minecraft_data_api]: 配置文件已加载
 [MCDR] [2024-10-18 13:12:10.818] [TaskExecutor/INFO] [mcdr_server.py:294(load_plugins)]: 共加载: §78§r 个插件; 已加载插件数: §710§r
 [MCDR] [2024-10-18 13:12:10.820] [MainThread/INFO] [mcdr_server.py:409(start_server)]: 正在启动服务端，启动参数为 'java -Xms5G -Xmx5G -Dfile.encoding=UTF-8 -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8 -jar fabric-1.21.1.jar'
 [MCDR] [2024-10-18 13:12:10.827] [MainThread/INFO] [mcdr_server.py:491(__on_server_start)]: 服务端正在以 PID 1742 运行中
 [MCDR] [2024-10-18 13:15:19.423] [TaskExecutor/INFO] [plugin_manager.py:703(refresh_changed_plugins_action)]: 刷新所有变更的插件中
 [MCDR] [2024-10-19 05:00:02.796] [MainThread/INFO] [mcdr_server.py:497(__on_server_stop)]: 服务端进程返回代码: 0
 [MCDR] [2024-10-19 05:00:02.797] [MainThread/INFO] [mcdr_server.py:515(__on_server_stop)]: 服务端已关闭
 [MCDR] [2024-10-19 05:00:02.797] [MainThread/INFO] [mcdr_server.py:654(__on_mcdr_stop)]: 正在关闭 MCDR
 [MCDR] [2024-10-19 05:00:02.797] [APR@0800/INFO] [reloader.py:118(thread_loop)] [auto_plugin_reloader]: Auto Plugin Reloader @ 0800 stopped
 [MCDR] [2024-10-19 05:00:02.797] [MainThread/INFO] [console_handler.py:306(stop_kits)]: 正在关闭高级控制台
 [MCDR] [2024-10-19 05:00:03.164] [MainThread/INFO] [mcdr_server.py:662(__on_mcdr_stop)]: bye
```

**Comment by Fallen-Breath** [comment]
配置文件填写错误，请检查那些类型为 `Duration` 的时间长度字段。你把某个字段的值设为了非法的 `null`

**Comment by Mingxi-Lin** [comment]
> 配置文件填写错误，请检查那些类型为 `Duration` 的时间长度字段。你把某个字段的值设为了非法的 `null`

解决了，把备份功能里的`jitter`的值设成了`null`，改成`"0s"`就好了，谢谢。
