### ISSUE TITLE
无法跨盘回档

### ISSUE THREAD

**Issue by addre98** [TISUnion/PrimeBackup#5]
### 环境
MCDR版本2.12.2
PrimeBackup版本1.3.0
Python版本3.11.4
### 日志

```
[TaskExecutor/INFO]: [PB] 正在确认回档任务
[MCDR] [2023-12-16 01:02:02] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 10秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:03] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 9秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:04] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 8秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:05] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 7秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:06] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 6秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:07] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 5秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:08] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 4秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:09] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 3秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:10] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 2秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:11] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 1秒后将§c回档§r至备份#1: 第一备份
[MCDR] [2023-12-16 01:02:12] [PB@9e69-worker-heavy/INFO] [prime_backup]: Wait for server to stop
[MCDR] [2023-12-16 01:02:12] [TaskExecutor/INFO]: rcon 已断开连接
[MCDR] [2023-12-16 01:02:16] [MainThread/INFO]: 服务端进程返回代码: 0
[MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Creating backup of existing files to avoid idiot
[MCDR] [2023-12-16 01:02:16] [MainThread/INFO]: 服务端已关闭
[MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Creating backup Backup(id=None, timestamp=1702659736038526200, creator='prime_backup:pre_restore', comment='__pb_translated__:pre_restore:1', targets=['world'], tags={'pre_restore_backup': True}, file_raw_size_sum=None, file_stored_size_sum=None) on ['world']
[MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Create backup #3 done, +85 blobs (size 148.27MiB / 200.66MiB)
[MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Restoring to backup #1 (fail_soft=False, verify_blob=True)
[MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Exporting Backup(id=1, timestamp=1702656034046077500, creator='player:Real_Infinistar', comment='第一备份', targets=['world'], tags={}, file_raw_size_sum=486159721, file_stored_size_sum=275769298) to directory server
[MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/WARNING] [prime_backup]: Error occurs during export to directory, applying rollback
[MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/ERROR] [prime_backup]: Task <prime_backup.mcdr.task.backup.restore_backup_task.RestoreBackupTask object at 0x000001B1C9C2F770> run error
Traceback (most recent call last):
  File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\mcdr\task_manager.py", line 54, in run_task
    ret = holder.task.run()
          ^^^^^^^^^^^^^^^^^
  File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\mcdr\task\backup\restore_backup_task.py", line 97, in run
    ).run()
      ^^^^^
  File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\action\export_backup_action.py", line 48, in run
    failures = self._export_backup(session, backup)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\action\export_backup_action.py", line 243, in _export_backup
    trash_bin.add(target_path, Path(target))
  File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\action\export_backup_action.py", line 92, in add
    src_path.rename(dst_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1363, in rename
    os.rename(self, target)
OSError: [WinError 17] 系统无法将文件移到不同的磁盘驱动器。: 'server\\world' -> 'E:\\backup\\pb_files\\Creative\\temp\\export_dir_5832_8300\\world'
[MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO]: [PB] 任务回档执行失败, 见控制台以了解错误详情
```

### 复现
在Windows上将`storage_root`与`backup`的`source_root`设置为不同两块盘，备份并回档
![Screenshot_20231216_015421](https://github.com/TISUnion/PrimeBackup/assets/111131309/4937a3da-647a-414d-8371-398992a72c0f)

**Comment by addre98** [comment]
> os.rename无法跨盘 `[MCDR] [2023-12-16 01:02:02] [TaskExecutor/INFO]: [PB] 正在确认回档任务 [MCDR] [2023-12-16 01:02:02] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 10秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:03] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 9秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:04] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 8秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:05] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 7秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:06] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 6秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:07] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 5秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:08] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 4秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:09] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 3秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:10] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 2秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:11] [PB@9e69-worker-heavy/INFO] [prime_backup]: [PB] !!! 1秒后将§c回档§r至备份#1: 第一备份 [MCDR] [2023-12-16 01:02:12] [PB@9e69-worker-heavy/INFO] [prime_backup]: Wait for server to stop [MCDR] [2023-12-16 01:02:12] [TaskExecutor/INFO]: rcon 已断开连接 [MCDR] [2023-12-16 01:02:16] [MainThread/INFO]: 服务端进程返回代码: 0 [MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Creating backup of existing files to avoid idiot [MCDR] [2023-12-16 01:02:16] [MainThread/INFO]: 服务端已关闭 [MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Creating backup Backup(id=None, timestamp=1702659736038526200, creator='prime_backup:pre_restore', comment='__pb_translated__:pre_restore:1', targets=['world'], tags={'pre_restore_backup': True}, file_raw_size_sum=None, file_stored_size_sum=None) on ['world'] [MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Create backup #3 done, +85 blobs (size 148.27MiB / 200.66MiB) [MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Restoring to backup #1 (fail_soft=False, verify_blob=True) [MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO] [prime_backup]: Exporting Backup(id=1, timestamp=1702656034046077500, creator='player:Real_Infinistar', comment='第一备份', targets=['world'], tags={}, file_raw_size_sum=486159721, file_stored_size_sum=275769298) to directory server [MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/WARNING] [prime_backup]: Error occurs during export to directory, applying rollback [MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/ERROR] [prime_backup]: Task <prime_backup.mcdr.task.backup.restore_backup_task.RestoreBackupTask object at 0x000001B1C9C2F770> run error Traceback (most recent call last): File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\mcdr\task_manager.py", line 54, in run_task ret = holder.task.run() ^^^^^^^^^^^^^^^^^ File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\mcdr\task\backup\restore_backup_task.py", line 97, in run ).run() ^^^^^ File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\action\export_backup_action.py", line 48, in run failures = self._export_backup(session, backup) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\action\export_backup_action.py", line 243, in _export_backup trash_bin.add(target_path, Path(target)) File "plugins\PrimeBackup-v1.3.0.pyz\prime_backup\action\export_backup_action.py", line 92, in add src_path.rename(dst_path) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1363, in rename os.rename(self, target) OSError: [WinError 17] 系统无法将文件移到不同的磁盘驱动器。: 'server\\world' -> 'E:\\backup\\pb_files\\Creative\\temp\\export_dir_5832_8300\\world' [MCDR] [2023-12-16 01:02:16] [PB@9e69-worker-heavy/INFO]: [PB] 任务回档执行失败, 见控制台以了解错误详情`
