### ISSUE TITLE
Could we change the accuracy of timestamp?

### ISSUE THREAD

**Issue by TimmyFengcreater** [TISUnion/PrimeBackup#51]
> !!pb
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: ======== Prime Backup v1.8.3 ========
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: A powerful backup plugin for MCDR, an advanced backup solution for your Minecraft world
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: [Common Commands]
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb: Display the welcome page
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb help [<what>]: Display help message of all / given command
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb make [<comment>]: Make a backup. <comment> is an optional comment message         
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb back [<backup_id>]: Restore to the given backup. See !!pb help back for detailed help 
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb list [...]: List backups with given filters. See !!pb help list for detailed help
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb show <backup_id>: Show detailed information of the given backup                   
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb rename <backup_id> <comment>: Modify the comment of the given backup              
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb delete <backup_id> [<backup_id>...]: Delete the given backup. You can enter multiple backup IDs
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb confirm: Confirm the current task execution
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: !!pb abort: Abort the current task execution
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: [Latest 0 Backups]
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: [Quick Actions]
[MCDR] [14:12:49] [PB@3ee1-worker-light/INFO]: [Create a new backup]                                                                  
> !!pb make
[MCDR] [14:12:56] [PB@3ee1-worker-heavy/INFO] [prime_backup]: [PB] Creating backup, please wait
[Server] [14:12:56] [Server thread/INFO]: Automatic saving is now disabled
[Server] [14:12:56] [Server thread/INFO]: Saving the game (this may take a moment!)
[Server] [14:12:56] [pool-2-thread-1/INFO]: [EasyAuth]: Saving database
[Server] [14:12:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [14:12:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [14:12:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[Server] [14:12:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [14:12:56] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[Server] [14:12:56] [Server thread/INFO]: Saved the game
[MCDR] [14:12:56] [PB@3ee1-worker-heavy/INFO] [prime_backup]: Scanning file for backup creation at path 'Desktop/Minecraft-Server/Minecraft-1.19.2-Server-Fabric-Mods', targets: ['world']
[MCDR] [14:12:56] [PB@3ee1-worker-heavy/INFO] [prime_backup]: Creating backup for ['world'] at path 'Desktop/Minecraft-Server/Minecraft-1.19.2-Server-Fabric-Mods', file cnt 374, timestamp 1735625576435056268, creator 'console:', comment '', tags {}
[MCDR] [14:12:57] [PB@3ee1-worker-heavy/WARNING] [prime_backup]: Error occurs during backup creation, applying rollback               
[MCDR] [14:12:57] [PB@3ee1-worker-heavy/ERROR] [prime_backup]: Task <prime_backup.mcdr.task.backup.create_backup_task.CreateBackupTask object at 0x7f4548b72330> run error                               
Traceback (most recent call last):
  File "Desktop/Minecraft-Server/Minecraft-1.19.2-Server-Fabric-Mods/MCDR-related/MCDR-plugins/PrimeBackup-v1.8.3-fix.pyz/prime_backup/mcdr/task_manager.py", line 79, in run_task
    ret = holder.task.run()
          ^^^^^^^^^^^^^^^^^
  File "Desktop/Minecraft-Server/Minecraft-1.19.2-Server-Fabric-Mods/MCDR-related/MCDR-plugins/PrimeBackup-v1.8.3-fix.pyz/prime_backup/mcdr/task/backup/create_backup_task.py", line 51, in run
    backup = action.run()
             ^^^^^^^^^^^^
  File "Desktop/Minecraft-Server/Minecraft-1.19.2-Server-Fabric-Mods/MCDR-related/MCDR-plugins/PrimeBackup-v1.8.3-fix.pyz/prime_backup/action/create_backup_action.py", line 608, in run
    raise e
  File "Desktop/Minecraft-Server/Minecraft-1.19.2-Server-Fabric-Mods/MCDR-related/MCDR-plugins/PrimeBackup-v1.8.3-fix.pyz/prime_backup/action/create_backup_action.py", line 550, in run
    with DbAccess.open_session() as session:
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "Desktop/Minecraft-Server/Minecraft-1.19.2-Server-Fabric-Mods/MCDR-related/MCDR-plugins/PrimeBackup-v1.8.3-fix.pyz/prime_backup/db/access.py", line 76, in open_session
    with Session(cls.__ensure_engine()) as session, session.begin():
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 147, in __exit__
    with util.safe_reraise():
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 145, in __exit__
    self.commit()
  File "<string>", line 2, in commit
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1936, in _exec_single_context
    self.dialect.do_executemany(
  File "/home/FTBC60/mcenv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 938, in do_executemany
    cursor.executemany(statement, parameters)
OverflowError: Python int too large to convert to SQLite INTEGER
[MCDR] [14:12:57] [PB@3ee1-worker-heavy/INFO]: [PB] Task create backup execution error, see console for more error                    
[Server] [14:12:57] [Server thread/INFO]: Automatic saving is now enabled
[Prime Backup 报错.txt](https://github.com/user-attachments/files/18279945/Prime.Backup.txt)

**Comment by Fallen-Breath** [comment]
What do you want to express? Please express it clearly and logically

- If you found an issue where PB is not working correctly, in addition to providing logs, please also provide a minimal reproducible environment and steps, including PB version, MCDR version, system version, PB configuration, and steps to reproduce
- If you wish to discuss and adjust the internal implementation of PB, please describe your motivation, explain the issues with the current design, and tell me the necessity of the changes you want

**Comment by Fallen-Breath** [comment]
用户诉求的真实场景实际为 #52
